### ISSUE TITLE
Bug: Typescript definition for Orb Import constructor doesn't match source

### ISSUE THREAD

**Issue by johnmurphy01** [CircleCI-Public/circleci-config-sdk-ts#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have pulled down the current latest alpha version `0.9.0-alpha.16`. I am attempting to add the slack orb and add a custom job for the `notify_build_completion` job. I used the unit test within the repo to recreate configuration of an `OrbImport` but I'm getting an error when I try to generate YAML:

```
Error: Error while parsing -
Missing type property on parameter: parameters
at errorParsing (/Users/johnmurphy/messaging-gateway/node_modules/@circleci/circleci-config-sdk/dist/webpack:/CircleCI/src/lib/Config/exports/Parsing.ts:58:10)
    at parseParameter (/Users/johnmurphy/messaging-gateway/node_modules/@circleci/circleci-config-sdk/dist/webpack:/CircleCI/src/lib/Components/Parameters/parsers/index.ts:52:13)
    at map (/Users/johnmurphy/messaging-gateway/node_modules/@circleci/circleci-config-sdk/dist/webpack:/CircleCI/src/lib/Components/Parameters/parsers/index.ts:127:7)
    at Array.map (<anonymous>)
    at Object.parseParameterList (/Users/johnmurphy/messaging-gateway/node_modules/@circleci/circleci-config-sdk/dist/webpack:/CircleCI/src/lib/Components/Parameters/parsers/index.ts:126:37)
    at map (/Users/johnmurphy/messaging-gateway/node_modules/@circleci/circleci-config-sdk/dist/webpack:/CircleCI/src/lib/Orb/exports/OrbImport.ts:65:38)
    at Array.map (<anonymous>)
    at parseImportManifest (/Users/johnmurphy/messaging-gateway/node_modules/@circleci/circleci-config-sdk/dist/webpack:/CircleCI/src/lib/Orb/exports/OrbImport.ts:64:44)
    at new t.OrbImport (/Users/johnmurphy/messaging-gateway/node_modules/@circleci/circleci-config-sdk/dist/webpack:/CircleCI/src/lib/Orb/exports/OrbImport.ts:43:19)
    at Object.<anonymous> (/Users/johnmurphy/messaging-gateway/.circleci/orbs/slack-orb.ts:13:25)
```

### Minimum reproduction code

n/a

### Steps to reproduce

1. Pull down `0.9.0-alpha.16` from NPM
2. View the type definitions for OrbImport
3. Notice that the `manifest` parameter is optional and is listed after the `version`. In the source, `manifest` is not optional and is listed before the `version`

I think this is why the command is failing? Or that's my hunch anyway

### Expected behavior

Adding a manifest with custom job parameters to an orb should not cause a crash and should instead generate YAML.

### CircleCI Config SDK version

0.9.0-alpha.16

### Node.js version

16.16.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

### Other

```ts
const manifest: types.orb.OrbImportManifest = {
  jobs: {
    notify_build_completion: new parameters.CustomParametersList([
      new parameters.CustomParameter('success_message', 'string'),
    ]),
  },
  commands: {},
  executors: {},
};
export const slackOrb = new orb.OrbImport(
  '',
  'circleci',
  'slack',
  '3.4.2',
  manifest,
);
```

Constructor of my type definition file: 
```ts
constructor(alias: string, namespace: string, orb: string, version: string, manifest?: OrbImportManifest, description?: string, display?: OrbDisplayMeta);
```

Constructor of the source file:
```ts
constructor(
    alias: string,
    namespace: string,
    orb: string,
    manifest: OrbImportManifest,
    version: string,
    description?: string,
    display?: OrbDisplayMeta,
  ) 
```

**Comment by Jaryt** [comment]
Hi @johnmurphy01 Thank you for this report! The latest release of the sdk still has the parser coupled with it, which we are separating into their own packages. This could be the reason the source file is out of sync with the type definition, and will be patched with the next release. There is a way to pull the orb manifest without having to write one manually, but we'll need to verify the best way to support this kind of functionality before diving deeper into that.

**Comment by johnmurphy01** [comment]
@Jaryt this appears to be resolved and working with the newest alpha release (`0.9.0-alpha.19`)

**Comment by Jaryt** [comment]
@johnmurphy01 Indeed! We should be releasing the config parser here shortly, which will provide you with an OrbManifestParser. We're also working on a way of providing easy access to generating these orb manifests. It is quite simple to create one yourself by taking the orb source, running it from a YAML to JSON parser, and then stripping it of the non-parameter values. This is only the start for orb support, but we may provide out of the box support for popular orbs in the future.
